#!/usr/bin/env node
var argv = process.argv
if (argv.length < 3 || argv.length > 4) {
  process.stderr.write('Usage: cftemplate <template> [context]\n')
  process.exit(1) }
else {
  var cftemplate = require('./')
  var fs = require('fs')
  var path = require('path')
  var templateFile = argv[2]
  var contextFile = argv[3]
  var context = (
    contextFile ?
      JSON.parse(fs.readFileSync(contextFile)) :
      { } )
  cftemplate(
    fs.readFileSync(templateFile).toString(),
    path.dirname(templateFile),
    context,
    function(error, output) {
      process.stdout.write(output) }) }
